### ISSUE TITLE
Can not view the converted Markdown result

### ISSUE THREAD

**Issue by kerna60** [jzillmann/pdf-to-markdown#66]
Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at jqmini.js:1:53
VM96:405 Edge Translation started
single-file-hooks-frames.js:1  OTS parsing error: glyf: Failed to parse table
e.FontFace @ single-file-hooks-frames.js:1
bundle.js:2 Warning: Failed to load font 'g_d0_f956': 'SyntaxError: Invalid font data in ArrayBuffer.'.
single-file-hooks-frames.js:1  OTS parsing error: glyf: Failed to parse table
e.FontFace @ single-file-hooks-frames.js:1
bundle.js:2 Warning: Failed to load font 'g_d0_f961': 'SyntaxError: Invalid font data in ArrayBuffer.'.
single-file-hooks-frames.js:1  OTS parsing error: glyf: Failed to parse table
e.FontFace @ single-file-hooks-frames.js:1
bundle.js:2 Warning: Failed to load font 'g_d0_f981': 'SyntaxError: Invalid font data in ArrayBuffer.'.
single-file-hooks-frames.js:1  OTS parsing error: glyf: Failed to parse table
e.FontFace @ single-file-hooks-frames.js:1
bundle.js:2 Warning: Failed to load font 'g_d0_f991': 'SyntaxError: Invalid font data in ArrayBuffer.'.
pdf2md.morethan.io/:1  Uncaught (in promise) Unsupported headline level: 7 (supported are 1-6)
2pdf2md.morethan.io/:1  Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
bundle.js:2  Uncaught TypeError: Cannot read properties of null (reading 'getHostNode')
    at Object.getHostNode (bundle.js:2:564541)
    at l.getHostNode (bundle.js:2:522842)
    at Object.getHostNode (bundle.js:2:564541)
    at Object.updateChildren (bundle.js:2:519030)
    at Y._reconcilerUpdateChildren (bundle.js:2:560442)
    at Y._updateChildren (bundle.js:2:561369)
    at Y.updateChildren (bundle.js:2:561267)
    at Y._updateDOMChildren (bundle.js:2:537299)
    at Y.updateComponent (bundle.js:2:535523)
    at Y.receiveComponent (bundle.js:2:535076)
3pdf2md.morethan.io/:1  Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
2bundle.js:2  Uncaught TypeError: Cannot read properties of null (reading 'getHostNode')
    at Object.getHostNode (bundle.js:2:564541)
    at l.getHostNode (bundle.js:2:522842)
    at Object.getHostNode (bundle.js:2:564541)
    at Object.updateChildren (bundle.js:2:519030)
    at Y._reconcilerUpdateChildren (bundle.js:2:560442)
    at Y._updateChildren (bundle.js:2:561369)
    at Y.updateChildren (bundle.js:2:561267)
    at Y._updateDOMChildren (bundle.js:2:537299)
    at Y.updateComponent (bundle.js:2:535523)
    at Y.receiveComponent (bundle.js:2:535076)

**Comment by kerna60** [comment]
I can't submit screenshots in any way, either by pasting or uploading an attachment

**Comment by kerna60** [comment]
This is the F12 page error message I submitted, unfortunately I don't understand what it means

**Comment by vicrpr9** [comment]
Same issue here, I tried Chrome after Safari.

**Comment by darkcheftar** [comment]
Apparently, there are 6 levels of heading H1 through H6 but the pdf you provided had H7?

**Comment by engimine** [comment]
me too
